projects:
  AuthAction:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: blsukcgi45c33jgqlt75qxrqmu
      endpoints:
        prod: >-
          https://k7gpxpleeffkblta7hyg7zljp4.appsync-api.us-east-1.amazonaws.com/graphql
