// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://k7gpxpleeffkblta7hyg7zljp4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-1:120b6697-d0b0-4bc1-8a66-4f22f215e885",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_U1ysVIIlq",
    "aws_user_pools_web_client_id": "27eehnv3iv4q76ag02a99ppo7h"
};


export default awsmobile;
